import Head from 'next/head'

/**
 * Header component.
 */
export default function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className="text-2xl font-bold">Welcome to Next.js!</h1>
      </header>
    </>
  )
}
